(function(){
  const productKey='lamunlai-products',cartKey='lamunlai-cart';
  const initial=[
    {id:'tote',name:'กระเป๋าผ้า Everyday Tote',category:'กระเป๋าผ้า',detail:'ผ้าฝ้ายทอมือ · สีดินเผา',description:'กระเป๋าผ้าทอมือทรงเรียบง่ายสำหรับทุกวัน ขนาดกำลังพอดี ใส่โน้ตบุ๊ก 13 นิ้วได้ พร้อมช่องกระเป๋าเล็กด้านใน',price:890,color:'sand',icon:'👜'},
    {id:'pillow',name:'ปลอกหมอนลายตาราง',category:'ของแต่งบ้าน',detail:'ผ้าฝ้ายธรรมชาติ · Sage green',description:'ปลอกหมอนผ้าฝ้ายธรรมชาติลายตาราง ช่วยเติมความอบอุ่นให้มุมพักผ่อนของคุณ',price:650,color:'green',icon:'🏠'},
    {id:'bloom',name:'กระเป๋าใส่เครื่องเขียน Bloom',category:'ของชิ้นเล็ก',detail:'ผ้าคอตตอน · ปักมือ',description:'กระเป๋าผ้าคอตตอนใบเล็ก ปักมืออย่างตั้งใจ เหมาะสำหรับเก็บเครื่องเขียนและของใช้ชิ้นโปรด',price:420,color:'beige',icon:'🎀'}
  ];
  const load=()=>JSON.parse(localStorage.getItem(productKey)||'null')||initial,save=x=>localStorage.setItem(productKey,JSON.stringify(x));
  const cart=()=>JSON.parse(localStorage.getItem(cartKey)||'[]');
  const money=n=>'฿ '+Number(n).toLocaleString('th-TH');
  const count=()=>cart().reduce((sum,item)=>sum+item.quantity,0);
  function updateCartCount(){document.querySelectorAll('.count').forEach(el=>el.textContent=count())}
  function saveCart(items){const products=load(),normalized=items.map(item=>{const product=products.find(candidate=>candidate.id===item.id)||item,stock=stockOf(product),quantity=Math.max(0,Number(item.quantity)||0);return {...product,...item,stock,quantity:Math.min(quantity,stock)}}).filter(item=>item.quantity>0);localStorage.setItem(cartKey,JSON.stringify(normalized));updateCartCount()}
  function stockOf(product){const stock=Number(product&&product.stock);return Number.isFinite(stock)?Math.max(0,stock):0}
  function addToCart(product,quantity=1){const currentProduct=load().find(item=>item.id===product.id)||product,items=cart(),existing=items.find(x=>x.id===currentProduct.id),current=existing?existing.quantity:0,available=Math.max(0,stockOf(currentProduct)-current),added=Math.min(Math.max(0,Number(quantity)||0),available);if(added){if(existing)existing.quantity+=added;else items.push({...currentProduct,quantity:added});saveCart(items);updateCartCount()}return {added,available}}
  async function syncStocks(){if(!window.supabaseReady){setTimeout(syncStocks,250);return}try{const db=await window.supabaseReady,{data,error}=await db.from('products').select('id,slug,stock,active');if(error||!data){console.warn('Unable to refresh stock',error);return}const lookup=new Map;data.forEach(x=>{lookup.set(x.id,x);if(x.slug)lookup.set(x.slug,x)});const products=load().map(product=>{const remote=lookup.get(product.id);return remote?{...product,stock:remote.active?(Number(remote.stock)||0):0,active:remote.active}:product});save(products);const corrected=cart().map(item=>{const remote=lookup.get(item.id),stock=remote?(remote.active?Number(remote.stock)||0:0):0;return {...item,stock,quantity:Math.min(item.quantity,stock)};}).filter(item=>item.quantity>0);saveCart(corrected);return products}catch(error){console.warn('Unable to refresh stock',error)}}
  window.catalog={load,save,money,cart,saveCart,count,addToCart,updateCartCount,stockOf,syncStocks};
  window.renderCatalog=function(filter='ทั้งหมด'){
    const target=document.querySelector('#product-list');if(!target)return;const items=load().filter(x=>filter==='ทั้งหมด'||x.category===filter);target.innerHTML='';
    if(!items.length){target.innerHTML='<p>ยังไม่มีสินค้าในหมวดนี้</p>';return}
    items.forEach(x=>{const card=document.createElement('a');card.className='card';card.href='product.html?id='+encodeURIComponent(x.id);const visual=x.image?'<img class="product-photo" alt="">':`<span class="product-emoji">${x.icon||'✦'}</span>`;card.innerHTML=`<div class="card-img ${x.color||'beige'}">${visual}</div><h3></h3><small></small><div class="price"></div>`;if(x.image){const image=card.querySelector('img');image.src=x.image;image.alt=x.name}card.querySelector('h3').textContent=x.name;card.querySelector('small').textContent=x.detail;card.querySelector('.price').textContent=money(x.price);target.append(card)});
  };
  updateCartCount();
  addEventListener('storage',event=>{if(event.key===cartKey)updateCartCount()});
  addEventListener('load',()=>{updateCartCount();syncStocks().then(()=>{if(typeof window.renderCart==='function')window.renderCart()})});
  document.addEventListener('click',event=>{const button=event.target;if(button.id==='add-button'){event.preventDefault();event.stopImmediatePropagation();const id=new URLSearchParams(location.search).get('id'),product=load().find(item=>item.id===id),quantity=Number(document.getElementById('quantity')?.textContent)||1,result=product?addToCart(product,quantity):{added:0};const message=document.getElementById('add-message');if(message)message.textContent=result.added===quantity?'เพิ่มสินค้าในตะกร้าแล้ว ✓':'เพิ่มได้ตามจำนวนสต๊อกที่เหลือเท่านั้น';const quantityEl=document.getElementById('quantity');if(quantityEl)quantityEl.textContent='1';return}if(button.closest('.detail .qty')&&button.textContent.trim()==='+'){const id=new URLSearchParams(location.search).get('id'),product=load().find(item=>item.id===id),quantityEl=document.getElementById('quantity');if(product&&quantityEl&&Number(quantityEl.textContent)>=stockOf(product)){event.preventDefault();event.stopImmediatePropagation();const message=document.getElementById('add-message');if(message)message.textContent='สินค้าในสต๊อกมีจำนวนเท่านี้';}}},true);
})();
